--------------------------------------------------------
--  File created - Friday-January-24-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ARCLIENTREMARKS
--------------------------------------------------------

  CREATE TABLE "ARCLIENTREMARKS" 
   (	"ARCLIENTREMARKSID" NUMBER(10,0), 
	"CLIENT_ID" CHAR(6), 
	"AUTO_KEY" NUMBER(10,0), 
	"REMARKS" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1471220876708613" 
 LOB ("REMARKS") STORE AS SECUREFILE (
  TABLESPACE "APEX_1471220876708613" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index SYS_C0012409
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0012409" ON "ARCLIENTREMARKS" ("ARCLIENTREMARKSID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1471220876708613" ;
--------------------------------------------------------
--  DDL for Trigger ARCLIENTREMARKS_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ARCLIENTREMARKS_SEQ_TR" 
 BEFORE INSERT ON ArClientRemarks FOR EACH ROW
  WHEN (NEW.ArClientRemarksID IS NULL) BEGIN
 SELECT ArClientRemarks_seq.NEXTVAL INTO :NEW.ArClientRemarksID FROM DUAL;
END;

/
ALTER TRIGGER "ARCLIENTREMARKS_SEQ_TR" ENABLE;
--------------------------------------------------------
--  Constraints for Table ARCLIENTREMARKS
--------------------------------------------------------

  ALTER TABLE "ARCLIENTREMARKS" MODIFY ("ARCLIENTREMARKSID" NOT NULL ENABLE);
  ALTER TABLE "ARCLIENTREMARKS" ADD PRIMARY KEY ("ARCLIENTREMARKSID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1471220876708613"  ENABLE;
