--------------------------------------------------------
--  File created - Friday-January-24-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ARCLIENTNOTES
--------------------------------------------------------

  CREATE TABLE "ARCLIENTNOTES" 
   (	"ARCLIENTNOTESID" NUMBER(10,0), 
	"CLIENT_ID" CHAR(6), 
	"USER_ID" VARCHAR2(3), 
	"SUBJECT" VARCHAR2(50), 
	"NOTE" VARCHAR2(1024)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1471220876708613" ;
--------------------------------------------------------
--  DDL for Index SYS_C0012399
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0012399" ON "ARCLIENTNOTES" ("ARCLIENTNOTESID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1471220876708613" ;
--------------------------------------------------------
--  DDL for Trigger ARCLIENTNOTES_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ARCLIENTNOTES_SEQ_TR" 
 BEFORE INSERT ON ArClientNotes FOR EACH ROW
  WHEN (NEW.ArClientNotesID IS NULL) BEGIN
 SELECT ArClientNotes_seq.NEXTVAL INTO :NEW.ArClientNotesID FROM DUAL;
END;

/
ALTER TRIGGER "ARCLIENTNOTES_SEQ_TR" ENABLE;
--------------------------------------------------------
--  Constraints for Table ARCLIENTNOTES
--------------------------------------------------------

  ALTER TABLE "ARCLIENTNOTES" MODIFY ("ARCLIENTNOTESID" NOT NULL ENABLE);
  ALTER TABLE "ARCLIENTNOTES" ADD PRIMARY KEY ("ARCLIENTNOTESID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1471220876708613"  ENABLE;
