--------------------------------------------------------
--  File created - Friday-January-24-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ARCONTACT
--------------------------------------------------------

  CREATE TABLE "ARCONTACT" 
   (	"ARCONTACTID" NUMBER(10,0), 
	"CLIENT_ID" CHAR(6), 
	"CONTACT_TYPE" CHAR(1), 
	"CONTACT" VARCHAR2(30), 
	"TITLE" VARCHAR2(30), 
	"PHONE" VARCHAR2(23), 
	"CELL_PHONE" VARCHAR2(23), 
	"FAX" VARCHAR2(13), 
	"CHANGED_DATE" CHAR(8), 
	"CHANGED_TIME" CHAR(6), 
	"CRM_REC_ID" CHAR(15), 
	"EMAIL" VARCHAR2(254), 
	"RMK_KEY_CONTACT" NUMBER(10,0), 
	"RESVD_EMAIL" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1471220876708613" ;
--------------------------------------------------------
--  DDL for Index SYS_C0012428
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0012428" ON "ARCONTACT" ("ARCONTACTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1471220876708613" ;
--------------------------------------------------------
--  DDL for Index IDX_ARCONTACT_CLIENT_ID
--------------------------------------------------------

  CREATE INDEX "IDX_ARCONTACT_CLIENT_ID" ON "ARCONTACT" ("CLIENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1471220876708613" ;
--------------------------------------------------------
--  DDL for Trigger ARCONTACT_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ARCONTACT_SEQ_TR" 
 BEFORE INSERT ON ArContact FOR EACH ROW
  WHEN (NEW.ArContactID IS NULL) BEGIN
 SELECT ArContact_seq.NEXTVAL INTO :NEW.ArContactID FROM DUAL;
END;

/
ALTER TRIGGER "ARCONTACT_SEQ_TR" ENABLE;
--------------------------------------------------------
--  Constraints for Table ARCONTACT
--------------------------------------------------------

  ALTER TABLE "ARCONTACT" MODIFY ("ARCONTACTID" NOT NULL ENABLE);
  ALTER TABLE "ARCONTACT" ADD PRIMARY KEY ("ARCONTACTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1471220876708613"  ENABLE;
