--------------------------------------------------------
--  File created - Friday-January-24-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ARINVOICE
--------------------------------------------------------

  CREATE TABLE "ARINVOICE" 
   (	"ARINVOICEID" NUMBER(10,0), 
	"CLIENT_ID" CHAR(6), 
	"YEAR" VARCHAR2(4), 
	"INVOICE_ID" CHAR(11), 
	"INVOICE_DATE" CHAR(8), 
	"DISCOUNT_DATE" CHAR(8), 
	"REFERENCE" VARCHAR2(10), 
	"DATE_ENTERED" CHAR(8), 
	"CLIENT_PO" VARCHAR2(20), 
	"LAST_PMT_REFERENCE" VARCHAR2(10), 
	"LAST_PAYMENT_DATE" CHAR(8), 
	"POSTED_DATE_AR" CHAR(8), 
	"POSTED_DATE_GL" CHAR(8), 
	"SHIPTO_ID" CHAR(11), 
	"TAX_ID" CHAR(15), 
	"CONSULTANT_ID" CHAR(3), 
	"CONSULTANT_2_ID" CHAR(3), 
	"USER_ID" VARCHAR2(3), 
	"TAXREPORT_NUMBER" VARCHAR2(6), 
	"INVOICE_BATCH" CHAR(6), 
	"LAST_CHECK_NUMBER" VARCHAR2(10), 
	"EXPENSE_PERIOD" NUMBER(3,0), 
	"BATCH_LIST_FLG" CHAR(1), 
	"CLOSED_FLG" CHAR(1), 
	"FINANCE_CHARGE_FLG" CHAR(1), 
	"TAXREPORT_FLG" CHAR(1), 
	"OE_FLG" CHAR(1), 
	"STATEMENT_CYCLE" CHAR(1), 
	"NET_DAYS" NUMBER(3,0), 
	"TAX_DETAIL_ID" NUMBER(5,0), 
	"AMOUNT" BINARY_DOUBLE, 
	"DISCOUNT" BINARY_DOUBLE, 
	"LAST_PAYMENT_AMOUNT" BINARY_DOUBLE, 
	"LAST_DISCOUNT_AMOUNT" BINARY_DOUBLE, 
	"TOTAL_PAYMENTS" BINARY_DOUBLE, 
	"TOTAL_DISCOUNTS" BINARY_DOUBLE, 
	"TOTAL_WRITEOFF" BINARY_DOUBLE, 
	"GROSS_PROFIT" BINARY_DOUBLE, 
	"TAX_AMOUNT" BINARY_DOUBLE, 
	"FREIGHT_AMOUNT" BINARY_DOUBLE, 
	"RES_FIN_CHG" BINARY_DOUBLE, 
	"RES_FIN_CHG_PCT" BINARY_DOUBLE, 
	"PAID_DAYS" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1471220876708613" ;
--------------------------------------------------------
--  DDL for Index SYS_C0012592
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0012592" ON "ARINVOICE" ("ARINVOICEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1471220876708613" ;
--------------------------------------------------------
--  DDL for Index INVOICE_ID
--------------------------------------------------------

  CREATE INDEX "INVOICE_ID" ON "ARINVOICE" ("ARINVOICEID", "INVOICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1471220876708613" ;
--------------------------------------------------------
--  DDL for Index ARINVOICE_CLIENT_ID
--------------------------------------------------------

  CREATE INDEX "ARINVOICE_CLIENT_ID" ON "ARINVOICE" ("CLIENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1471220876708613" ;
--------------------------------------------------------
--  DDL for Index ARINVOICE_INVOICE_DATE
--------------------------------------------------------

  CREATE INDEX "ARINVOICE_INVOICE_DATE" ON "ARINVOICE" ("INVOICE_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1471220876708613" ;
--------------------------------------------------------
--  DDL for Trigger ARINVOICE_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ARINVOICE_SEQ_TR" 
 BEFORE INSERT ON ArInvoice FOR EACH ROW
  WHEN (NEW.ArInvoiceID IS NULL) BEGIN
 SELECT ArInvoice_seq.NEXTVAL INTO :NEW.ArInvoiceID FROM DUAL;
END;

/
ALTER TRIGGER "ARINVOICE_SEQ_TR" ENABLE;
--------------------------------------------------------
--  Constraints for Table ARINVOICE
--------------------------------------------------------

  ALTER TABLE "ARINVOICE" MODIFY ("ARINVOICEID" NOT NULL ENABLE);
  ALTER TABLE "ARINVOICE" ADD PRIMARY KEY ("ARINVOICEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1471220876708613"  ENABLE;
