--------------------------------------------------------
--  File created - Friday-January-24-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ARTAX
--------------------------------------------------------

  CREATE TABLE "ARTAX" 
   (	"ARTAXID" NUMBER(10,0), 
	"TAX_ID" CHAR(15), 
	"DESCRIPTION" VARCHAR2(30), 
	"GROUP_ID" CHAR(14), 
	"STATE" VARCHAR2(4), 
	"GEO_CODE" CHAR(10), 
	"COUNTY" CHAR(25), 
	"CITY" CHAR(25), 
	"BASED_ON_TOTAL_FLG" CHAR(1), 
	"TAX_FREIGHT_FLG" CHAR(1), 
	"CREATED_BY_IMP" CHAR(1), 
	"RATE_USE_TAX" BINARY_DOUBLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1471220876708613" ;
--------------------------------------------------------
--  DDL for Index SYS_C0012638
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0012638" ON "ARTAX" ("ARTAXID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1471220876708613" ;
--------------------------------------------------------
--  DDL for Trigger ARTAX_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ARTAX_SEQ_TR" 
 BEFORE INSERT ON ArTax FOR EACH ROW
  WHEN (NEW.ArTaxID IS NULL) BEGIN
 SELECT ArTax_seq.NEXTVAL INTO :NEW.ArTaxID FROM DUAL;
END;
/
ALTER TRIGGER "ARTAX_SEQ_TR" ENABLE;
--------------------------------------------------------
--  Constraints for Table ARTAX
--------------------------------------------------------

  ALTER TABLE "ARTAX" MODIFY ("ARTAXID" NOT NULL ENABLE);
  ALTER TABLE "ARTAX" ADD PRIMARY KEY ("ARTAXID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_1471220876708613"  ENABLE;
